import '../../styles/style.css';
import '../../styles/actors.css';
import '../../styles/quizResult.css';

export const actorsData = [
  {
    question: 'What is the name of this actor?',
    a: 'Tom Dillon',
    b: 'Willem Dafoe ',
    c: 'Arron Something',
    d: 'Brad Pitt',
    correct: 'b',
    imgSource: '/assets/images/actors/Willem_Dafoe.jpg',
  },
  {
    question: 'What is the name of this actress?',
    a: 'Ashley Brooke',
    b: 'Tina Fare',
    c: 'Kelly Reilly ',
    d: 'Winona Ryder',
    correct: 'c',
    imgSource: '/assets/images/actors/Kelly_Reilly.jpg',
  },
  {
    question: 'What is the name of this actor?',
    a: 'Andrew Garfield ',
    b: 'Tobey McGuire',
    c: 'Charlie Sheen',
    d: 'John Void',
    correct: 'a',
    imgSource: '/assets/images/actors/Andrew_Garfield.jpg',
  },
  {
    question: 'What is the name of this actress?',
    a: 'Angelina Jolie ',
    b: 'Gwyneth Pathrow',
    c: 'Zoe Saldana',
    d: 'Monica Belluca',
    correct: 'a',
    imgSource: '/assets/images/actors/Angelina_Jolie.jpg',
  },
  {
    question: 'What is the name of this actress?',
    a: 'Viola Davis',
    b: 'Meryl Streep',
    c: 'Carrie-Anne Moss  ',
    d: 'Charlize Theron',
    correct: 'c',
    imgSource: '/assets/images/actors/Carrie-Anne_Moss.jpg',
  },
  {
    question: 'What is the name of this actor?',
    a: 'Denzel Washington',
    b: 'Tom Hanks',
    c: 'Tom Cruise',
    d: 'Tom Holland ',
    correct: 'd',
    imgSource: '/assets/images/actors/Tom_Holland.jpg',
  },
  {
    question: 'What is the name of this actor?',
    a: 'Leonardo DiCaprio ',
    b: 'Robert De Niro',
    c: 'Christian Bale',
    d: 'Liam Neeson',
    correct: 'a',
    imgSource: '/assets/images/actors/Leonardo_DiCaprio.jpg',
  },
  {
    question: 'What is the name of this actor?',
    a: 'Morgan Freeman',
    b: 'Al Pacino',
    c: 'Keanu Reeves ',
    d: 'Clint Eastwood',
    correct: 'c',
    imgSource: '/assets/images/actors/Keanu_Reeves.jpg',
  },
  {
    question: 'What is the name of this actor?',
    a: 'Johnny Depp',
    b: 'Anthony Hopkins',
    c: 'Brad Pitt',
    d: 'Jason Statham ',
    correct: 'd',
    imgSource: '/assets/images/actors/Jason_Statham.jpg',
  },
  {
    question: 'What is the name of this actress?',
    a: 'Jennifer Landon ',
    b: 'Nicole Kidman',
    c: 'Cate Blanchett',
    d: 'Sandra Bullock',
    correct: 'a',
    imgSource: '/assets/images/actors/Jennifer_Landon.jpg',
  },
];
