export const soundsData = [
  {
    question: 'Do You know what movie is this music from?',
    a: 'Frozen',
    b: 'dummyData',
    c: 'dummyData',
    d: 'dummyData',
    correct: 'a',
    soundSource: '/assets/sounds/frozen.mp3',
  },
  {
    question: 'Do You know what movie is this music from?',
    a: 'dummyData',
    b: 'dummyData',
    c: 'Batman',
    d: 'dummyData',
    correct: 'c',
    soundSource: '/assets/sounds/batman1989.mp3',
  },
  {
    question: 'Do You know what movie is this music from?',
    a: 'dummyData',
    b: 'Turning Forty',
    c: 'dummyData',
    d: 'dummyData',
    correct: 'b',
    soundSource: '/assets/sounds/czterdziestolatek.mp3',
  },
  {
    question: 'Do You know what movie is this music from?',
    a: 'dummyData',
    b: 'Edward Scissorhands',
    c: 'dummyData',
    d: 'dummyData',
    correct: 'b',
    soundSource: '/assets/sounds/edwardScissorhands.mp3',
  },
  {
    question: 'Do You know what movie is this music from?',
    a: 'dummyData',
    b: 'dummyData',
    c: 'dummyData',
    d: 'Hannibal',
    correct: 'd',
    soundSource: '/assets/sounds/hannibal.mp3',
  },
  {
    question: 'Do You know what movie is this music from?',
    a: 'Home Alone',
    b: 'dummyData',
    c: 'dummyData',
    d: 'dummyData',
    correct: 'a',
    soundSource: '/assets/sounds/homeAlone.mp3',
  },
  {
    question: 'Do You know what movie is this music from?',
    a: "The Queen's Gambit",
    b: 'dummyData',
    c: 'dummyData',
    d: 'dummyData',
    correct: 'a',
    soundSource: '/assets/sounds/queensGambit.mp3',
  },
  {
    question: 'Do You know what movie is this music from?',
    a: 'dummyData',
    b: 'dummyData',
    c: 'dummyData',
    d: 'The Mission',
    correct: 'd',
    soundSource: '/assets/sounds/mission.mp3',
  },
  {
    question: 'Do You know what movie is this music from?',
    a: 'dummyData',
    b: 'dummyData',
    c: 'dummyData',
    d: 'Master Thaddeus: The Last Foray in Lithuania',
    correct: 'd',
    soundSource: '/assets/sounds/panTadeusz.mp3',
  },
  {
    question: 'Do You know what movie is this music from?',
    a: 'dummyData',
    b: 'dummyData',
    c: 'Our Folks',
    d: 'dummyData',
    correct: 'c',
    soundSource: '/assets/sounds/samiSwoi.mp3',
  },
];
